channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - websockify
  - syncthing
  - pip
  - pip:
    - jupyterlab-git
    - jupyterlab-favorites
    - jupyter-desktop-server
    - jupyter-syncthing-proxy
    - gh-scoped-creds
