channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - websockify
  - syncthing
  - jupyterlab-favorites
  - jupyterlab-git
  - gh-scoped-creds

  - intake
  - intake-esm
  - intake-geopandas
  - intake-stac
  - intake-xarray

  - pip
  - pip:
    - jupyter-desktop-server
    - jupyter-syncthing-proxy
