channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - websockify
  - syncthing
  - jupyterlab-favorites
  - jupyterlab-git
  - gh-scoped-creds
  - pip
  - pip:
    - jupyter-desktop-server
    - jupyter-syncthing-proxy
